<div class="container-fluid">

    <legend>Graduate Assistant Application</legend>

    <p>
        <span class="required-star">*</span> = required section
    </p>

    <form id="graduate_assistant_application_form" name="graduate_assistant_application_form" method="POST" enctype="multipart/form-data" action="/gar/application/create">

        <div class="row-fluid"> <!-- Start Row -->
            
            <div class="well">
                
                <div class="row-fluid">
                    <h3>
                        <span class="required-star">*</span> Tell Us About Yourself
                    </h3>
                </div>
                
                <div class="row-fluid">
                    <div class="span3">
                        <div class="control-group">
                            <label class="control-label" for="first_name">First Name:</label>
                            <div class="controls">
                                <input type="text" id="first_name" name="first_name" />
                            </div>
                        </div>
                    </div>
                    <div class="span3 offset1">
                        <div class="control-group">
                            <label class="control-label" for="last_name">Last Name:</label>
                            <div class="controls">
                                <input type="text" id="last_name" name="last_name" />
                            </div>  
                        </div>
                    </div>
                    <div class="span3 offset1">
                        <div class="control-group">
                            <label class="control-label" for="email_address">E-mail Address:</label>
                            <div class="controls">
                                <div class="input-prepend">
                                    <span class="add-on"><i class="icon-envelope"></i></span>
                                    <input type="text" id="email_address" name="email_address" class="prepend-text-field" />
                                </div>
                            </div>
                        </div>
                    </div>                
                </div>
                
                <div class="row-fluid">
                    <div class="span3">
                        <div class="control-group">
                            <label class="control-label" for="telephone_number">Telephone Number:</label>
                            <div class="controls">
                                <div class="input-prepend">
                                    <span class="add-on"><i class="icon-phone"></i></span>
                                    <input type="text" id="telephone_number" name="telephone_number" class="prepend-text-field" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
            </div>
            
        </div> <!-- End Row -->
        
        <div class="row-fluid"> <!-- Start Row -->
            
            <div class="well">

                <div class="row-fluid">
                    <h3>Your Mailing Information</h3>
                </div>
                
                <div class="row-fluid">
                    <div class="span3">
                        <div class="control-group">
                            <label class="control-label" for="address_one">Address One:</label>
                            <div class="controls">
                                <input type="text" id="address_one" name="address_one" />
                            </div>
                        </div>
                    </div>
                </div>
                
                <div class="row-fluid">
                    <div class="span3">
                        <div class="control-group">
                            <label class="control-label" for="address_two">Address Two:</label>
                            <div class="controls">
                                <input type="text" id="address_two" name="address_two" />
                            </div>  
                        </div>
                    </div>
                </div>
                
                <div class="row-fluid">
                    <div class="span3">
                        <div class="control-group">
                            <label class="control-label" for="city">City:</label>
                            <div class="controls">
                                <input type="text" id="city" name="city" />
                            </div>
                        </div>
                    </div>
                    <div class="span3 offset1">
                        <div class="control-group">
                            <label class="control-label" for="state_province_region">State/Province/Region:</label>
                            <div class="controls">
                                <input type="text" id="state_province_region" name="state_province_region" />
                            </div>
                        </div>
                    </div>
                    <div class="span3 offset1">
                        <div class="control-group">
                            <label class="control-label" for="zip_postal_code">ZIP/Postal Code:</label>
                            <div class="controls">
                                <input type="text" id="zip_postal_code" name="zip_postal_code" />
                            </div>
                        </div>
                    </div>
                </div>
                
                <div class="row-fluid">
                    <div class="span3">
                        <div class="control-group">
                            <label class="control-label" for="country">Country:</label>
                            <div class="controls">
                                <input type="text" id="country" name="country" />
                            </div>
                        </div>
                    </div>
                </div>

            </div> <!-- Well End -->

        </div> <!--Row End-->

        <div class="row-fluid"> <!--Row Start-->

            <div class="well">

                <div class="row-fluid">
                    <h3>                   
                        <span class="required-star">*</span> Your Education Information
                    </h3>
                </div>

                <div class="row-fluid">
                     <div class="span3">
                        <div class="control-group">
                            <label class="control-label" for="undergraduate_institution">Undergraduate Institution:</label>
                            <div class="controls">
                                <input type="text" id="undergraduate_institution" name="undergraduate_institution" />
                            </div>
                        </div>
                    </div>
                    <div class="span3 offset1">
                        <div class="control-group">
                            <label class="control-label" for="graduate_institution">Graduate Institution:</label>
                            <div class="controls">
                                <input type="text" id="graduate_institution" name="graduate_institution" />
                            </div>
                        </div>
                    </div>
                     <div class="span3 offset1">
                        <div class="control-group">
                            <label class="control-label" for="graduate_program">Graduate Program:</label>
                            <div class="controls">
                                <input type="text" id="graduate_program" name="graduate_program" />
                            </div>
                        </div>
                    </div>
                </div>

            </div> <!-- Well End -->

        </div> <!--Row End-->

        <div class="row-fluid"> <!-- Row Start -->

            <div class="well">

                <div class="row-fluid">
                   <h3>                   
                       <span class="required-star">*</span> Which Positions Are You Applying For?
                   </h3>
                </div>

                <div class="row-fluid">
                    <div class="checkbox-group-container">
                        <?php
                            foreach($this->positions as $position)
                            {
                                 print "<label class='checkbox'>"
                                      . "<input type='checkbox' name='position_id[]' id='"
                                      . $position->getPositionId() . "' "
                                      . "value='" . $position->getPositionId() . "' "
                                      . "class='checkbox-group' />"
                                      . " " . $position->getPositionName() . " (" . $position->getDepartmentName() . ")"
                                      . "</label>";
                            }
                        ?>
                    </div>
                </div>

            </div> <!-- Well End -->

        </div> <!-- Row End -->

        <div class="row-fluid">

            <div class="well">

                <div class="row-fluid">
                    <h3>
                        <span class="required-star">*</span> Your References
                    </h3>
                    
                    <p class="bold">
                    Please indicate name, mailing address, email address, telephone number 
                    and the type of reference being supplied (work, academic or personal)
                    </p>
                </div>

                <div class="row-fluid">
                    <div class="span12">
                        <div class="control-group">
                            <label class="control-label" for="reference_one">Reference One:</label>
                            <div class="controls">
                                <textarea rows="5" cols="5" id="reference_one" name="reference_one" class="span12 textarea-validation"></textarea>
                            </div>
                        </div>
                    </div>
                </div>
                
                <div class="row-fluid">
                    <div class="span12">
                        <div class="control-group">
                            <label class="control-label" for="reference_two">Reference Two:</label>
                            <div class="controls">
                                <textarea rows="5" cols="5" id="reference_two" name="reference_two" class="span12 textarea-validation"></textarea>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row-fluid">
                    <div class="span12">
                        <div class="control-group">
                            <label class="control-label" for="reference_three">Reference Three:</label>
                            <div class="controls">
                                <textarea rows="5" cols="5" id="reference_three" name="reference_three" class="span12 textarea-validation"></textarea>
                            </div>
                        </div>
                    </div>
                </div>

            </div> <!-- Well End -->

        </div> <!-- Row End -->

        <div class="row-fluid">

            <div class="well">

                <div class="row-fluid">
                    <h3>
                       <span class="required-star">*</span> Essay Questions
                    </h3>
                    
                    <p class="bold">Please limit responses to no more than 1500 words</p>
                </div>

                <div class="row-fluid">
                    <div class="span12">
                        <div class="control-group">
                            <label class="control-label" for="personal_qualities_question">How will your personal qualities influence and contribute to the RIT community?</label>
                            <div class="controls">
                                <textarea rows="5" cols="5" id="personal_qualities_question" name="personal_qualities_question" class="span12 textarea-validation"></textarea>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span12">
                        <div class="control-group">
                            <label class="control-label" for="prior_experiences_question">How has your prior experiences prepared you for this assistantship opportunity?</label>
                            <div class="controls">
                                <textarea rows="5" cols="5" id="prior_experiences_question" name="prior_experiences_question" class="span12 textarea-validation"></textarea>
                            </div>
                        </div>
                    </div>
                </div>

            </div> <!-- End Well -->

        </div> <!-- End Row -->

        <div class="row-fluid">

            <div class="well">

                <div class="row-fluid">
                    <h3>
                        <span class="required-star">*</span> Resume and Cover Letter Attachment
                    </h3>
                    
                    <p class="bold">Word & PDF file types accepted only (.doc, .docx, .pdf)</p>
                </div>
                
                <div class="row-fluid">
                   <div class="fileupload fileupload-new" data-provides="fileupload">
                    <div class="input-append">
                      <div class="uneditable-input span3">
                          <i class="icon-file fileupload-exists"></i>
                          <span class="fileupload-preview"></span>
                      </div>
                        <span class="btn btn-file">
                            <span class="fileupload-new">Select file</span>
                            <span class="fileupload-exists">Change</span>
                            <input type="file" name="resume_cover_letter_attachment" id="resume_cover_letter_attachment" />
                        </span>
                        <a href="#" class="btn fileupload-exists" data-dismiss="fileupload">Remove</a>
                    </div>
                  </div>
                </div>

            </div>
        </div>
        
         <div class="row-fluid">

            <div class="well">

                <div class="row-fluid">
                    <h3>Disability Accommodation</h3>
                </div>
                
                <div class="row-fluid">
                    RIT provides reasonable accommodation to applicants with disabilities, veterans or wounded warriors where appropriate. 
                    If you need reasonable accommodation for any part of the application and hiring process, please contact the Human Resources 
                    office at 585-475-2424 or email your request to Careers@rit.edu. 
                    Determinations on requests for reasonable accommodation will be made on a case-by-case basis.
                </div>

            </div>
        </div>

        <div class="form-actions">                
            <button type="submit" class="btn btn-primary btn-large">Submit</button>
        </div>
        
    </form>
</div>