
<div class="page-header">
    <h1>Graduate Assistant Recruiting @ RIT</h1>
</div>

<div class="row-fluid">
    <div class="well">
        <h3>
            Thank you for submitting your Graduate Assistant Application @ RIT. 
            You will be contacted shortly if your qualifications meet our requirements.
        </h3>
    </div>
</div>

<div class="row-fluid">
    <div class="pull-right">
        <a href="/gar/authentication/logoff" class="btn btn-large btn-primary"><i class="icon-signout icon-white"></i> Sign-Out</a>
    </div>
</div>

<hr>

<footer>
    <p>&copy; Rochester Institute of Technology 2013</p>
</footer>
