<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Search\Module'                                            => __DIR__ . '/Module.php',
    'Search\Controller\IndexController'                        => __DIR__ . '/src/Search/Controller/IndexController.php',
    'Applicant\ControllerFactory\ApplicationControllerFactory' => __DIR__ . '/src/Search/ControllerFactory/SearchControllerFactory.php',
    'Solr\BaseDocument'                                        => __DIR__ . '/src/Search/Solr/BaseDocument.php',
    'Solr\Document\iSolrDocument'                              => __DIR__ . '/src/Search/Solr/document/iSolrDocument.interface.php',
    'Solr\Document\SolrDocument'                               => __DIR__ . '/src/Search/Solr/document/SolrDocument.class.php',
    'Solr\Facet\iSolrFlatFacet'                                => __DIR__ . '/src/Search/Solr/facet/flat/iSolrFlatFacet.php',
    'Solr\Facet\SolrFlatFacet'                                 => __DIR__ . '/src/Search/Solr/facet/flat/SolrFlatFacet.php',
    'Solr\Facet\iSolrFacet'                                    => __DIR__ . '/src/Search/Solr/facet/iSolrFacet.php',
    'Solr\Facet\SolrFacet'                                     => __DIR__ . '/src/Search/Solr/facet/SolrFacet.php',
    'Solr\GAR\Search\SearchResultCollection'                   => __DIR__ . '/src/Search/Solr/GAR/Search/SearchResultCollection.php',
    'Solr\GAR\Search\SearchResultDocument'                     => __DIR__ . '/src/Search/Solr/GAR/Search/SearchResultDocument.php',
    'Solr\Highlight\SolrHighlight'                             => __DIR__ . '/src/Search/Solr/highlight/SolrHighlight.php',
    'Solr\Highlight\SolrHighlightedDocumentDecorator'          => __DIR__ . '/src/Search/Solr/highlight/SolrHighlightedDocumentDecorator.php',
    'SolrPagerFactory'                                         => __DIR__ . '/src/Search/Solr/pager/SolrPagerFactory.class.php',
    'Solr\SolrClient'                                          => __DIR__ . '/src/Search/Solr/SolrClient.php',
    'Solr\Url\SolrUrl'                                         => __DIR__ . '/src/Search/Solr/url/SolrUrl.php',
    'Search\View\Helper\SolrUrl'                               => __DIR__ . '/src/Search/View/Helper/SolrUrl.php',
    'Solr\BreadCrumb\SolrBreadCrumb'                           => __DIR__ . '/src/Search/Solr/breadcrumb/SolrBreadCrumb.php',
    'Solr\Url\SolrSearchUrl'                                   => __DIR__ . '/src/Search/Solr/url/SolrSearchUrl.php'
);