<div class="page-header">
    <h1>Graduate Assistant Recruiting @ RIT</h1>
</div>
<p class="lead">
    Welcome to the Graduate Assistant Recruiting Application @ RIT for 2013-2014.
    <br/>
    Register to start your application or sign-in to update your application.
</p>
<p>
    For help please click <a href="mailto:drgrla@rit.edu?subject=GA Recruiting Application Help">here</a>
</p>

<?php if(count($flashMessages)) :?>
<div class="alert alert-info alert-block message-container">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
        <ul>
            <?php foreach($flashMessages as $msg) :?>
                <span> <i class="icon-info-sign"></i></span>
                <?php echo $msg . "<br/>"?>
            <?php endforeach;?>
        </ul>
</div>
<?php endif;?>

<div class="row">
    <div class="span4 well">
        <form id="gar_registration_form" name="gar_registration_form" class="form-signin" method="POST" action="/gar/user/create">
            <h2 class="form-signin-heading">Register</h2>
            <input type="text" name="registration_email_address" id="registration_email_address" class="input-block-level" placeholder="Email address">
            <input type="password" name="registration_password" id="registration_password" class="input-block-level" placeholder="Verify Password">
            <input type="password" name="registration_verify_password" id="registration_verify_password" class="input-block-level" placeholder="Password">
            <button class="btn btn-large btn-primary" type="submit">Register &raquo;</button>
        </form>
    </div>
    <div class="span3 center-text">
        <div class="vertical-align-text">or</div>
    </div>
    <div class="span4 well">
        <form id="gar_login_form" name="gar_login_form" class="form-signin" method="POST" action="/gar/authentication/login">
            <h2 class="form-signin-heading">Sign-In</h2>
            <input type="text" name="login_email_address" id="login_email_address" class="input-block-level" placeholder="Email address">
            <input type="password" name="login_password" id="login_password" class="input-block-level" placeholder="Password">
            <button class="btn btn-large btn-primary" type="submit">Sign-In &raquo;</button>
        </form>
    </div>
</div>

<hr>

<footer>
    <p>&copy; Rochester Institute of Technology 2013</p>
</footer>